name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make

    - name: Build the library
      run: |
        make
      shell: bash

    - name: Run tests
      run: |
        make test
      shell: bash
